Create set.h
jattilainen/set_hse pull request #1
Opened 2019-06-06 17:54 UTC by jattilainen

2019-06-17 10:06 UTC, sartuhin requested changes

2019-06-17 10:06 UTC, sartuhin commented on set.h
> +        int height;
size_t?

2019-06-17 10:06 UTC, sartuhin commented on set.h
> +        if (height(v) > 50) {
Неименованная константа.

2019-06-17 10:06 UTC, sartuhin commented on set.h
> +            exit(0);
Не нужно.

2019-06-17 10:06 UTC, sartuhin commented on set.h
> +    size_t sz;
Зачем сокращать названия? Нужно наоборот делать их говорящими.

2019-06-17 10:06 UTC, sartuhin commented on set.h
> +    Node* removemin(Node* v) {
Почему где то в названиях есть _ а где то нет?

2019-06-18 18:21 UTC, jattilainen commented
https://official.contest.yandex.ru/contest/12783/run-report/20722365/

2019-06-23 06:48 UTC, sartuhin requested changes

2019-06-23 06:48 UTC, sartuhin commented on set.h
> +using namespace std;
Нельзя делать using всего std. Только то что используется должно быть.

2019-06-23 12:20 UTC, jattilainen commented
https://official.contest.yandex.ru/contest/12783/run-report/20739471/

2019-06-25 08:42 UTC, sartuhin approved these changes

2019-06-25 08:42 UTC, merged